<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../backend/Project1.Api/Project1.Api.csproj" />
    <ProjectReference Include="../../scripts/deploy/dotnet/Project1.MigrationExecutor/Project1.MigrationExecutor.csproj" />
  </ItemGroup>
</Project>
