// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project1.Api.Data;

#nullable disable

namespace Project1.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260829125253_AddPurchaseRequestWorkflowEngine")]
    partial class AddPurchaseRequestWorkflowEngine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project1.Api.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("Project1.Api.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("DefaultUnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ProductCategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("ReorderLevel")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("UnitOfMeasureId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Project1.Api.Entities.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ProductCategories", (string)null);
                });

            modelBuilder.Entity("Project1.Api.Entities.PurchaseRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Justification")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RequesterName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("RequiredDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RequestNumber")
                        .IsUnique();

                    b.ToTable("PurchaseRequests", (string)null);
                });

            modelBuilder.Entity("Project1.Api.Entities.PurchaseRequestItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("EstimatedUnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseRequestId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseRequestId", "ProductId")
                        .IsUnique();

                    b.ToTable("PurchaseRequestItems", (string)null);
                });

            modelBuilder.Entity("Project1.Api.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("Project1.Api.Entities.UnitOfMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("UnitsOfMeasure", (string)null);
                });

            modelBuilder.Entity("Project1.Api.Entities.Workflows.WorkflowActionInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FromStepInstanceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("RequiresComment")
                        .HasColumnType("bit");

                    b.Property<int>("SourceActionTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("ToStepInstanceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ToStepInstanceId");

                    b.HasIndex("FromStepInstanceId", "Code")
                        .IsUnique();

                    b.ToTable("WorkflowActionInstances", (string)null);
                });

            modelBuilder.Entity("Project1.Api.Entities.Workflows.WorkflowActionTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FromStepTemplateId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("RequiresComment")
                        .HasColumnType("bit");

                    b.Property<int>("ToStepTemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ToStepTemplateId");

                    b.HasIndex("FromStepTemplateId", "Code")
                        .IsUnique();

                    b.ToTable("WorkflowActionTemplates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "SUBMIT",
                            FromStepTemplateId = 1,
                            Name = "Submit",
                            RequiresComment = false,
                            ToStepTemplateId = 2
                        },
                        new
                        {
                            Id = 2,
                            Code = "APPROVE",
                            FromStepTemplateId = 2,
                            Name = "Approve department review",
                            RequiresComment = false,
                            ToStepTemplateId = 3
                        },
                        new
                        {
                            Id = 3,
                            Code = "REJECT",
                            FromStepTemplateId = 2,
                            Name = "Reject department review",
                            RequiresComment = true,
                            ToStepTemplateId = 5
                        },
                        new
                        {
                            Id = 4,
                            Code = "APPROVE",
                            FromStepTemplateId = 3,
                            Name = "Approve finance review",
                            RequiresComment = false,
                            ToStepTemplateId = 4
                        },
                        new
                        {
                            Id = 5,
                            Code = "REJECT",
                            FromStepTemplateId = 3,
                            Name = "Reject finance review",
                            RequiresComment = true,
                            ToStepTemplateId = 5
                        });
                });

            modelBuilder.Entity("Project1.Api.Entities.Workflows.WorkflowActionerInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionInstanceId")
                        .HasColumnType("int");

                    b.Property<string>("ActionerKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ActionerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ActionInstanceId");

                    b.ToTable("WorkflowActionerInstances", (string)null);
                });

            modelBuilder.Entity("Project1.Api.Entities.Workflows.WorkflowActionerTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionTemplateId")
                        .HasColumnType("int");

                    b.Property<string>("ActionerKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ActionerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ActionTemplateId");

                    b.ToTable("WorkflowActionerTemplates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionTemplateId = 1,
                            ActionerType = "Requester"
                        },
                        new
                        {
                            Id = 2,
                            ActionTemplateId = 2,
                            ActionerKey = "DEPARTMENT_APPROVER",
                            ActionerType = "Role"
                        },
                        new
                        {
                            Id = 3,
                            ActionTemplateId = 3,
                            ActionerKey = "DEPARTMENT_APPROVER",
                            ActionerType = "Role"
                        },
                        new
                        {
                            Id = 4,
                            ActionTemplateId = 4,
                            ActionerKey = "FINANCE_APPROVER",
                            ActionerType = "Role"
                        },
                        new
                        {
                            Id = 5,
                            ActionTemplateId = 5,
                            ActionerKey = "FINANCE_APPROVER",
                            ActionerType = "Role"
                        });
                });

            modelBuilder.Entity("Project1.Api.Entities.Workflows.WorkflowHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("ActionAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ActionBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ActionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ActionInstanceId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FromStepCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProcessInstanceId")
                        .HasColumnType("int");

                    b.Property<string>("ToStepCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessInstanceId", "ActionAtUtc");

                    b.ToTable("WorkflowHistory", (string)null);
                });

            modelBuilder.Entity("Project1.Api.Entities.Workflows.WorkflowProcessInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CurrentStepInstanceId")
                        .HasColumnType("int");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProcessTemplateId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TemplateCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TemplateVersion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcessTemplateId");

                    b.HasIndex("EntityType", "EntityId")
                        .IsUnique();

                    b.HasIndex("Status", "CurrentStepInstanceId");

                    b.ToTable("WorkflowProcessInstances", (string)null);
                });

            modelBuilder.Entity("Project1.Api.Entities.Workflows.WorkflowProcessTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code", "Version")
                        .IsUnique();

                    b.HasIndex("EntityType", "IsPublished", "IsActive");

                    b.ToTable("WorkflowProcessTemplates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PURCHASE_REQUEST",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EntityType = "PurchaseRequest",
                            IsActive = true,
                            IsPublished = true,
                            Name = "Purchase Request Approval",
                            PublishedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        });
                });

            modelBuilder.Entity("Project1.Api.Entities.Workflows.WorkflowStepInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsInitial")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProcessInstanceId")
                        .HasColumnType("int");

                    b.Property<int>("SourceStepTemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcessInstanceId", "Code")
                        .IsUnique();

                    b.ToTable("WorkflowStepInstances", (string)null);
                });

            modelBuilder.Entity("Project1.Api.Entities.Workflows.WorkflowStepTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsInitial")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProcessTemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcessTemplateId", "Code")
                        .IsUnique();

                    b.ToTable("WorkflowStepTemplates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "DRAFT",
                            DisplayOrder = 1,
                            IsInitial = true,
                            IsTerminal = false,
                            Name = "Draft",
                            ProcessTemplateId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "DEPARTMENT_REVIEW",
                            DisplayOrder = 2,
                            IsInitial = false,
                            IsTerminal = false,
                            Name = "Department Review",
                            ProcessTemplateId = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "FINANCE_REVIEW",
                            DisplayOrder = 3,
                            IsInitial = false,
                            IsTerminal = false,
                            Name = "Finance Review",
                            ProcessTemplateId = 1
                        },
                        new
                        {
                            Id = 4,
                            Code = "APPROVED",
                            DisplayOrder = 4,
                            IsInitial = false,
                            IsTerminal = true,
                            Name = "Approved",
                            ProcessTemplateId = 1
                        },
                        new
                        {
                            Id = 5,
                            Code = "REJECTED",
                            DisplayOrder = 5,
                            IsInitial = false,
                            IsTerminal = true,
                            Name = "Rejected",
                            ProcessTemplateId = 1
                        });
                });

            modelBuilder.Entity("Project1.Api.Entities.Product", b =>
                {
                    b.HasOne("Project1.Api.Entities.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project1.Api.Entities.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany("Products")
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductCategory");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("Project1.Api.Entities.PurchaseRequest", b =>
                {
                    b.HasOne("Project1.Api.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Project1.Api.Entities.PurchaseRequestItem", b =>
                {
                    b.HasOne("Project1.Api.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project1.Api.Entities.PurchaseRequest", "PurchaseRequest")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("PurchaseRequest");
                });

            modelBuilder.Entity("Project1.Api.Entities.Workflows.WorkflowActionInstance", b =>
                {
                    b.HasOne("Project1.Api.Entities.Workflows.WorkflowStepInstance", "FromStepInstance")
                        .WithMany("Actions")
                        .HasForeignKey("FromStepInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project1.Api.Entities.Workflows.WorkflowStepInstance", "ToStepInstance")
                        .WithMany()
                        .HasForeignKey("ToStepInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromStepInstance");

                    b.Navigation("ToStepInstance");
                });

            modelBuilder.Entity("Project1.Api.Entities.Workflows.WorkflowActionTemplate", b =>
                {
                    b.HasOne("Project1.Api.Entities.Workflows.WorkflowStepTemplate", "FromStepTemplate")
                        .WithMany("Actions")
                        .HasForeignKey("FromStepTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project1.Api.Entities.Workflows.WorkflowStepTemplate", "ToStepTemplate")
                        .WithMany()
                        .HasForeignKey("ToStepTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromStepTemplate");

                    b.Navigation("ToStepTemplate");
                });

            modelBuilder.Entity("Project1.Api.Entities.Workflows.WorkflowActionerInstance", b =>
                {
                    b.HasOne("Project1.Api.Entities.Workflows.WorkflowActionInstance", "ActionInstance")
                        .WithMany("Actioners")
                        .HasForeignKey("ActionInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionInstance");
                });

            modelBuilder.Entity("Project1.Api.Entities.Workflows.WorkflowActionerTemplate", b =>
                {
                    b.HasOne("Project1.Api.Entities.Workflows.WorkflowActionTemplate", "ActionTemplate")
                        .WithMany("Actioners")
                        .HasForeignKey("ActionTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionTemplate");
                });

            modelBuilder.Entity("Project1.Api.Entities.Workflows.WorkflowHistory", b =>
                {
                    b.HasOne("Project1.Api.Entities.Workflows.WorkflowProcessInstance", "ProcessInstance")
                        .WithMany("History")
                        .HasForeignKey("ProcessInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessInstance");
                });

            modelBuilder.Entity("Project1.Api.Entities.Workflows.WorkflowProcessInstance", b =>
                {
                    b.HasOne("Project1.Api.Entities.Workflows.WorkflowProcessTemplate", "ProcessTemplate")
                        .WithMany()
                        .HasForeignKey("ProcessTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProcessTemplate");
                });

            modelBuilder.Entity("Project1.Api.Entities.Workflows.WorkflowStepInstance", b =>
                {
                    b.HasOne("Project1.Api.Entities.Workflows.WorkflowProcessInstance", "ProcessInstance")
                        .WithMany("Steps")
                        .HasForeignKey("ProcessInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessInstance");
                });

            modelBuilder.Entity("Project1.Api.Entities.Workflows.WorkflowStepTemplate", b =>
                {
                    b.HasOne("Project1.Api.Entities.Workflows.WorkflowProcessTemplate", "ProcessTemplate")
                        .WithMany("Steps")
                        .HasForeignKey("ProcessTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessTemplate");
                });

            modelBuilder.Entity("Project1.Api.Entities.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Project1.Api.Entities.PurchaseRequest", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Project1.Api.Entities.UnitOfMeasure", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Project1.Api.Entities.Workflows.WorkflowActionInstance", b =>
                {
                    b.Navigation("Actioners");
                });

            modelBuilder.Entity("Project1.Api.Entities.Workflows.WorkflowActionTemplate", b =>
                {
                    b.Navigation("Actioners");
                });

            modelBuilder.Entity("Project1.Api.Entities.Workflows.WorkflowProcessInstance", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Project1.Api.Entities.Workflows.WorkflowProcessTemplate", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Project1.Api.Entities.Workflows.WorkflowStepInstance", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("Project1.Api.Entities.Workflows.WorkflowStepTemplate", b =>
                {
                    b.Navigation("Actions");
                });
#pragma warning restore 612, 618
        }
    }
}
